<?php
namespace app\index\controller;

use app\index\controller\Base;
use think\Config;

class Index extends Base
{
    Public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        return $this->redirect('/public/angular/index.html');
    }

    public function dashboard(){
        $return = [
            'data'=>[
                ['id'=>12,
                'name'=>'ASD']
            ]
        ];
        return json_encode($return);
    }
}
