<?php
namespace app\index\model;

use think\Model;

class WorkflowDefination extends Model
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}